version: '3.9'
services:
    express-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: puc-swe-project-api-container
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        volumes:
            - ./app.mjs:/app/app.mjs
            - ./.env:/app/.env
