export const menus = [
    {
        id: 1,
        title: 'Cadastro',
        descriptions: 'Cadastro de pacientes, médicos, especialidades e convênios',
        icon: 'mdi-form-select',
        color: 'primary',
        link: '/cadastro',
        active: true,
    },
    {
        id: 2,
        title: 'Consultas',
        descriptions: 'Agendamento de consultas, histórico e prontuário',
        icon: 'mdi-medical-bag',
        color: 'secondary',
        link: '/consultas',
        active: true,
    },
    {
        id: 3,
        title: 'Relatórios',
        descriptions: 'Relatórios de consultas, pacientes, médicos e convênios',
        icon: 'mdi-file-search-outline',
        color: 'info',
        // link: '/relatorios',
        active: false,
        message: 'Em breve',
    },
    {
        id: 4,
        title: 'Configurações',
        descriptions: 'Configurações do sistema, usuários e permissões',
        icon: 'mdi-cog-outline',
        color: 'warning',
        // link: '/configuracoes',
        active: false,
        message: 'Em breve',
    },
];
